
import React from 'react';
import { OreType, Item, Upgrade, ItemCategory, GameState } from './types';
import { GiGoldBar, GiCoalWagon, GiStoneBlock, GiGems, GiMineralPearls, GiFireGem, GiStoneAxe, GiHammerNails, GiAnvil, GiBroadsword, GiBattleAxe, GiCoins, GiMiningHelmet, GiFurnace, GiSellCard, GiPowerLightning, GiTwoCoins, GiMetalBar, GiTrashCan, GiMailShirt, GiShoulderArmor } from 'react-icons/gi';
import { FaPlus, FaGem } from 'react-icons/fa';

export const ORE_TIERS: OreType[] = [
    OreType.STONE,
    OreType.COPPER,
    OreType.TIN,
    OreType.IRON,
    OreType.GOLD,
    OreType.MYTHRIL,
    OreType.ADAMANTITE,
];

const getTier = (ore: OreType): number => ORE_TIERS.indexOf(ore);

export const ORE_ICONS: Record<OreType, React.ReactNode> = {
    [OreType.STONE]: <GiStoneBlock className="text-gray-500" />,
    [OreType.COAL]: <GiCoalWagon className="text-gray-400" />,
    [OreType.COPPER]: <GiCoins className="text-orange-500" />,
    [OreType.TIN]: <GiMetalBar className="text-slate-300" />,
    [OreType.BRONZE]: <GiMetalBar className="text-yellow-600" />,
    [OreType.IRON]: <GiMineralPearls className="text-slate-400" />,
    [OreType.GOLD]: <GiGoldBar className="text-yellow-500" />,
    [OreType.MYTHRIL]: <GiGems className="text-cyan-400" />,
    [OreType.ADAMANTITE]: <GiFireGem className="text-red-500" />,
};

export const ITEMS: Record<string, Item> = {
    // Tier 0: Stone
    stoneSword: {
        id: 'stoneSword',
        name: 'Stone Sword',
        description: 'A crude but effective sword made of stone.',
        recipe: { [OreType.STONE]: 10 },
        sellPrice: 15,
        icon: <GiBroadsword className="text-gray-500" />,
        category: ItemCategory.WEAPON,
        tier: getTier(OreType.STONE),
    },
    stonePickaxe: {
        id: 'stonePickaxe',
        name: 'Stone Pickaxe',
        description: 'A basic pickaxe for mining stone and other soft materials.',
        recipe: { [OreType.STONE]: 15 },
        sellPrice: 16,
        icon: <GiStoneAxe className="text-gray-500" />,
        category: ItemCategory.TOOL,
        tier: getTier(OreType.STONE),
    },
    // Universal Material
    bagOfCoal: {
        id: 'bagOfCoal',
        name: 'Bag of Coal',
        description: 'A bag of high-quality coal, ready for the forge or for sale.',
        recipe: { [OreType.COAL]: 20 },
        sellPrice: 25,
        icon: <GiCoalWagon className="text-gray-200" />,
        category: ItemCategory.MATERIAL,
        tier: getTier(OreType.COAL), // Will be -1, always available
    },
    // Tier 1: Copper
    copperIngot: {
        id: 'copperIngot',
        name: 'Copper Ingot',
        description: 'A refined bar of pure copper.',
        recipe: { [OreType.COPPER]: 30 },
        sellPrice: 0,
        icon: <GiMetalBar className="text-orange-500" />,
        category: ItemCategory.MATERIAL,
        tier: getTier(OreType.COPPER),
    },
    copperSword: {
        id: 'copperSword',
        name: 'Copper Sword',
        description: 'A simple sword, better than stone.',
        recipe: { 'copperIngot': 1, [OreType.COAL]: 1 },
        sellPrice: 60,
        icon: <GiBroadsword className="text-orange-500" />,
        category: ItemCategory.WEAPON,
        tier: getTier(OreType.COPPER),
    },
    copperPickaxe: {
        id: 'copperPickaxe',
        name: 'Copper Pickaxe',
        description: 'A soft but serviceable pickaxe, better than stone.',
        recipe: { 'copperIngot': 1, [OreType.COAL]: 2 },
        sellPrice: 65,
        icon: <GiStoneAxe className="text-orange-500" />,
        category: ItemCategory.TOOL,
        tier: getTier(OreType.COPPER),
    },
    copperChestplate: {
        id: 'copperChestplate',
        name: 'Copper Chestplate',
        description: 'Basic protection. Better than nothing.',
        recipe: { 'copperIngot': 2, [OreType.COAL]: 5 },
        sellPrice: 100,
        icon: <GiMailShirt className="text-orange-500" />,
        category: ItemCategory.ARMOR,
        tier: getTier(OreType.COPPER),
    },
    // Tier 2: Tin & Bronze
    tinIngot: {
        id: 'tinIngot',
        name: 'Tin Ingot',
        description: 'A refined bar of pure tin.',
        recipe: { [OreType.TIN]: 30 },
        sellPrice: 0,
        icon: <GiMetalBar className="text-slate-300" />,
        category: ItemCategory.MATERIAL,
        tier: getTier(OreType.TIN),
    },
    tinCan: {
        id: 'tinCan',
        name: 'Tin Can',
        description: 'A simple can. Surprisingly useful for... things.',
        recipe: { 'tinIngot': 1 },
        sellPrice: 15,
        icon: <GiTrashCan className="text-slate-300" />,
        category: ItemCategory.TOOL,
        tier: getTier(OreType.TIN),
    },
    bronzeIngot: {
        id: 'bronzeIngot',
        name: 'Bronze Ingot',
        description: 'Forge Copper and Tin into a strong alloy, used for crafting bronze items.',
        recipe: { [OreType.COPPER]: 16, [OreType.TIN]: 4 },
        sellPrice: 0,
        icon: ORE_ICONS[OreType.BRONZE],
        category: ItemCategory.MATERIAL,
        tier: getTier(OreType.TIN),
    },
    bronzeSword: {
        id: 'bronzeSword',
        name: 'Bronze Sword',
        description: 'A classic, reliable weapon for a new warrior.',
        recipe: { 'bronzeIngot': 8, [OreType.COAL]: 5 },
        sellPrice: 300,
        icon: <GiBroadsword className="text-yellow-600" />,
        category: ItemCategory.WEAPON,
        tier: getTier(OreType.TIN),
    },
    bronzePickaxe: {
        id: 'bronzePickaxe',
        name: 'Bronze Pickaxe',
        description: 'A sturdy tool capable of tough work.',
        recipe: { 'bronzeIngot': 12, [OreType.COAL]: 6 },
        sellPrice: 320,
        icon: <GiStoneAxe className="text-yellow-600" />,
        category: ItemCategory.TOOL,
        tier: getTier(OreType.TIN),
    },
    bronzeChestplate: {
        id: 'bronzeChestplate',
        name: 'Bronze Chestplate',
        description: 'Solid protection for a fledgling adventurer.',
        recipe: { 'bronzeIngot': 15, [OreType.COAL]: 8 },
        sellPrice: 500,
        icon: <GiMailShirt className="text-yellow-600" />,
        category: ItemCategory.ARMOR,
        tier: getTier(OreType.TIN),
    },
    // Tier 3: Iron
    ironIngot: {
        id: 'ironIngot',
        name: 'Iron Ingot',
        description: 'A foundational building block for strong tools and weapons.',
        recipe: { [OreType.IRON]: 30 },
        sellPrice: 0,
        icon: <GiMetalBar className="text-slate-400" />,
        category: ItemCategory.MATERIAL,
        tier: getTier(OreType.IRON),
    },
    ironSword: {
        id: 'ironSword',
        name: 'Iron Sword',
        description: 'A sturdy sword for a novice adventurer.',
        recipe: { 'ironIngot': 1, [OreType.COAL]: 2 },
        sellPrice: 450,
        icon: <GiBroadsword className="text-slate-400" />,
        category: ItemCategory.WEAPON,
        tier: getTier(OreType.IRON),
    },
    ironPickaxe: {
        id: 'ironPickaxe',
        name: 'Iron Pickaxe',
        description: 'A reliable pickaxe, the workhorse of any smithy.',
        recipe: { 'ironIngot': 1, [OreType.COAL]: 3 },
        sellPrice: 480,
        icon: <GiStoneAxe className="text-slate-400" />,
        category: ItemCategory.TOOL,
        tier: getTier(OreType.IRON),
    },
    ironChestplate: {
        id: 'ironChestplate',
        name: 'Iron Chestplate',
        description: 'Dependable armor. A true classic.',
        recipe: { 'ironIngot': 2, [OreType.COAL]: 4 },
        sellPrice: 650,
        icon: <GiMailShirt className="text-slate-400" />,
        category: ItemCategory.ARMOR,
        tier: getTier(OreType.IRON),
    },
    // Tier 4: Gold
    goldIngot: {
        id: 'goldIngot',
        name: 'Gold Ingot',
        description: 'A refined bar of pure gold.',
        recipe: { [OreType.GOLD]: 30 },
        sellPrice: 0,
        icon: <GiGoldBar className="text-yellow-500" />,
        category: ItemCategory.MATERIAL,
        tier: getTier(OreType.GOLD),
    },
    goldRing: {
        id: 'goldRing',
        name: 'Gold Ring',
        description: 'A shiny ring that fetches a good price.',
        recipe: { 'goldIngot': 1 },
        sellPrice: 150,
        icon: <FaGem className="text-yellow-400" />,
        category: ItemCategory.WEAPON,
        tier: getTier(OreType.GOLD),
    },
    goldSword: {
        id: 'goldSword',
        name: 'Gilded Sword',
        description: 'More for show than for battle, but very valuable.',
        recipe: { 'goldIngot': 1, [OreType.COAL]: 4 },
        sellPrice: 1000,
        icon: <GiBroadsword className="text-yellow-400" />,
        category: ItemCategory.WEAPON,
        tier: getTier(OreType.GOLD),
    },
    goldPickaxe: {
        id: 'goldPickaxe',
        name: 'Gilded Pickaxe',
        description: 'More decorative than durable, but it has a certain flair.',
        recipe: { 'goldIngot': 1, [OreType.COAL]: 5 },
        sellPrice: 1100,
        icon: <GiStoneAxe className="text-yellow-400" />,
        category: ItemCategory.TOOL,
        tier: getTier(OreType.GOLD),
    },
    goldChestplate: {
        id: 'goldChestplate',
        name: 'Gilded Chestplate',
        description: 'Opulent and surprisingly protective.',
        recipe: { 'goldIngot': 2, [OreType.COAL]: 6 },
        sellPrice: 1500,
        icon: <GiMailShirt className="text-yellow-400" />,
        category: ItemCategory.ARMOR,
        tier: getTier(OreType.GOLD),
    },
    // Tier 5: Mythril
     mythrilIngot: {
        id: 'mythrilIngot',
        name: 'Mythril Ingot',
        description: 'A refined bar of pure mythril.',
        recipe: { [OreType.MYTHRIL]: 30 },
        sellPrice: 0,
        icon: <GiMetalBar className="text-cyan-400" />,
        category: ItemCategory.MATERIAL,
        tier: getTier(OreType.MYTHRIL),
    },
    mythrilAxe: {
        id: 'mythrilAxe',
        name: 'Mythril Axe',
        description: 'A lightweight but incredibly sharp battle axe.',
        recipe: { 'mythrilIngot': 1, 'goldIngot': 1, [OreType.COAL]: 5 },
        sellPrice: 2500,
        icon: <GiBattleAxe className="text-cyan-400" />,
        category: ItemCategory.WEAPON,
        tier: getTier(OreType.MYTHRIL),
    },
    mythrilPickaxe: {
        id: 'mythrilPickaxe',
        name: 'Mythril Pickaxe',
        description: 'A magical pickaxe, unnaturally light and strong.',
        recipe: { 'mythrilIngot': 1, [OreType.COAL]: 8 },
        sellPrice: 2700,
        icon: <GiStoneAxe className="text-cyan-400" />,
        category: ItemCategory.TOOL,
        tier: getTier(OreType.MYTHRIL),
    },
    mythrilChestplate: {
        id: 'mythrilChestplate',
        name: 'Mythril Chestplate',
        description: 'As light as a feather, as hard as dragon scales.',
        recipe: { 'mythrilIngot': 1, [OreType.COAL]: 10 },
        sellPrice: 4000,
        icon: <GiMailShirt className="text-cyan-400" />,
        category: ItemCategory.ARMOR,
        tier: getTier(OreType.MYTHRIL),
    },
    // Tier 6: Adamantite
    adamantiteIngot: {
        id: 'adamantiteIngot',
        name: 'Adamantite Ingot',
        description: 'A refined bar of pure adamantite.',
        recipe: { [OreType.ADAMANTITE]: 30 },
        sellPrice: 0,
        icon: <GiMetalBar className="text-red-500" />,
        category: ItemCategory.MATERIAL,
        tier: getTier(OreType.ADAMANTITE),
    },
    adamantiteChestplate: {
        id: 'adamantiteChestplate',
        name: 'Adamantite Chestplate',
        description: 'Nearly indestructible chest armor.',
        recipe: { 'adamantiteIngot': 2, 'mythrilIngot': 1 },
        sellPrice: 9000,
        icon: <GiMailShirt className="text-red-500" />,
        category: ItemCategory.ARMOR,
        tier: getTier(OreType.ADAMANTITE),
    },
    adamantiteSword: {
        id: 'adamantiteSword',
        name: 'Adamantite Sword',
        description: 'An incredibly heavy and powerful sword.',
        recipe: { 'adamantiteIngot': 1, 'mythrilIngot': 1 },
        sellPrice: 6000,
        icon: <GiBroadsword className="text-red-500" />,
        category: ItemCategory.WEAPON,
        tier: getTier(OreType.ADAMANTITE),
    },
    adamantitePickaxe: {
        id: 'adamantitePickaxe',
        name: 'Adamantite Pickaxe',
        description: 'Can break through the toughest of rocks with ease.',
        recipe: { 'adamantiteIngot': 2, [OreType.COAL]: 20 },
        sellPrice: 6500,
        icon: <GiStoneAxe className="text-red-500" />,
        category: ItemCategory.TOOL,
        tier: getTier(OreType.ADAMANTITE),
    },
};

export const UPGRADES: Record<string, Upgrade> = {
    // Mining Upgrades
    miner: {
        id: 'miner',
        name: 'Miner',
        description: 'Hires a miner to automatically click the ore once per second.',
        cost: 100, // Base cost
        repeatable: true,
        apply: (s) => ({ ...s, autoMinerRate: s.upgrades.miner || 0 }),
        icon: <GiMiningHelmet />
    },
    reinforcedPicks: {
        id: 'reinforcedPicks',
        name: 'Reinforced Picks',
        description: 'Doubles the amount of ore gained per click. Max 3 tiers.',
        cost: 2000,
        repeatable: true,
        maxTiers: 3,
        apply: (s) => ({ ...s, orePerClick: s.orePerClick * 2 }),
        icon: <GiPowerLightning />
    },
    offlineMining: {
        id: 'offlineMining',
        name: 'Offline Mining',
        description: 'Earn a percentage of ores from auto-miners while offline. Max 5 tiers.',
        cost: (currentTier) => 25000 * Math.pow(2, currentTier), // Cost doubles each tier
        repeatable: true,
        maxTiers: 5,
        prereq: 'miner',
        apply: (s) => s, // Logic is handled on game load
        icon: <GiPowerLightning />
    },
    // Ore Tier Upgrades
    nextTier1: {
        id: 'nextTier1',
        name: 'Mine Deeper: Copper',
        description: 'Unlock the ability to mine Copper.',
        cost: 200,
        apply: (s) => ({ ...s, maxOreTier: 1, currentOreTier: 1 }),
        icon: ORE_ICONS[OreType.COPPER],
    },
    nextTier2: {
        id: 'nextTier2',
        name: 'Mine Deeper: Tin',
        description: 'Unlock the ability to mine Tin.',
        cost: 1000,
        prereq: 'nextTier1',
        apply: (s) => ({ ...s, maxOreTier: 2, currentOreTier: 2 }),
        icon: ORE_ICONS[OreType.TIN],
    },
    nextTier3: {
        id: 'nextTier3',
        name: 'Mine Deeper: Iron',
        description: 'Unlock the ability to mine Iron.',
        cost: 5000,
        prereq: 'nextTier2',
        apply: (s) => ({ ...s, maxOreTier: 3, currentOreTier: 3 }),
        icon: ORE_ICONS[OreType.IRON],
    },
    nextTier4: {
        id: 'nextTier4',
        name: 'Strike Gold!',
        description: 'Unlock the ability to mine Gold.',
        cost: 25000,
        prereq: 'nextTier3',
        apply: (s) => ({ ...s, maxOreTier: 4, currentOreTier: 4 }),
        icon: ORE_ICONS[OreType.GOLD],
    },
    nextTier5: {
        id: 'nextTier5',
        name: 'Find Mythril',
        description: 'Unlock the ability to mine Mythril.',
        cost: 100000,
        prereq: 'nextTier4',
        apply: (s) => ({ ...s, maxOreTier: 5, currentOreTier: 5 }),
        icon: ORE_ICONS[OreType.MYTHRIL],
    },
    nextTier6: {
        id: 'nextTier6',
        name: 'Unearth Adamantite',
        description: 'Unlock the ability to mine Adamantite.',
        cost: 500000,
        prereq: 'nextTier5',
        apply: (s) => ({ ...s, maxOreTier: 6, currentOreTier: 6 }),
        icon: ORE_ICONS[OreType.ADAMANTITE],
    },
    // Forging Upgrades
    furnace: {
        id: 'furnace',
        name: 'Furnace',
        description: 'Unlock the ability to smelt your Ores down into Refined Ingots!',
        cost: 500,
        apply: (s) => s, // Effect handled in UI
        icon: <GiFurnace />,
    },
    furnaceMKII: {
        id: 'furnaceMKII',
        name: 'Furnace MKII',
        description: 'Halves the ore cost for smelting ingots.',
        cost: 5000,
        prereq: 'furnace',
        apply: (s) => s, // Effect handled in game logic
        icon: <GiFurnace />,
    },
    toolForge: {
        id: 'toolForge',
        name: 'Tool Forge',
        description: 'Unlocks the ability to forge tools, like pickaxes.',
        cost: 250,
        apply: (s) => s, // Effect is handled in UI
        icon: <GiHammerNails />
    },
    armorersTable: {
        id: 'armorersTable',
        name: "Armorer's Table",
        description: "Unlock the ability to forge different armors for your adventurers!",
        cost: 2000,
        apply: (s) => s, // Effect is handled in UI
        icon: <GiShoulderArmor />,
    },
    betterAnvil: {
        id: 'betterAnvil',
        name: 'Mystical Anvil',
        description: 'Forge 2 Weapons for the cost of 1.',
        cost: 15000,
        apply: (s) => s, // Effect is handled in forge logic
        icon: <GiAnvil />
    },
    // Shop Upgrades
    masterSalesman: {
        id: 'masterSalesman',
        name: 'Master Salesman',
        description: 'Increases sell prices by 20%.',
        cost: 750,
        apply: (s) => ({...s, sellPriceMultiplier: s.sellPriceMultiplier * 1.2}),
        icon: <GiSellCard />
    }
};
